<a href="https://colab.research.google.com/github/DotBion/PyTorch-Practice/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim


0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [9]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
practens = torch.tensor([[[1,2,3,4],
                          [4,5,0,6],
                          [5,3,5,7]]])
practens

tensor([[[1, 2, 3, 4],
         [4, 5, 0, 6],
         [5, 3, 5, 7]]])

In [17]:
practens.ndim

3

In [18]:
practens.shape

torch.Size([1, 3, 4])

In [19]:
practens = torch.tensor([[[1,2],
                          [4,5],
                          [5,3]],])
practens

tensor([[[1, 2],
         [4, 5],
         [5, 3]]])

In [20]:
practens = torch.tensor([[[1,2,7],
                          [4,5,7],
                          [5,3,7]],
                         [[1,2,3],
                          [1,5,4],
                          [1,1,1]]])
practens

tensor([[[1, 2, 7],
         [4, 5, 7],
         [5, 3, 7]],

        [[1, 2, 3],
         [1, 5, 4],
         [1, 1, 1]]])

In [21]:
practens[1][2][2]

tensor(1)

### Random Tensors

In [22]:
# create a random tensor of size/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5177, 0.6967, 0.1553, 0.2503],
        [0.1199, 0.7678, 0.3542, 0.5571],
        [0.2792, 0.5564, 0.3089, 0.3438]])

In [23]:
random_tensor.ndim

2

In [24]:
torch.rand(size=(3,4))
#OR
torch.rand(3,4)

tensor([[0.4296, 0.3635, 0.3784, 0.9023],
        [0.5728, 0.3204, 0.9133, 0.2235],
        [0.4684, 0.4219, 0.5210, 0.8903]])

In [25]:
random_tensor = torch.rand(1,4,10)
random_tensor

tensor([[[0.7877, 0.0602, 0.2937, 0.2977, 0.8100, 0.7356, 0.0230, 0.1745,
          0.8445, 0.8767],
         [0.4466, 0.9570, 0.1914, 0.2843, 0.5002, 0.0456, 0.5361, 0.8878,
          0.3489, 0.6443],
         [0.7642, 0.0785, 0.6343, 0.8807, 0.5436, 0.0512, 0.2154, 0.8626,
          0.5239, 0.5257],
         [0.7289, 0.3194, 0.2707, 0.5599, 0.3284, 0.6551, 0.7630, 0.9538,
          0.1269, 0.7902]]])

In [26]:
random_tensor.ndim

3

In [27]:
#create a random tensor similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, widht, colour channels - RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

#or the colour channel may come a first
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

### zeores and ones

In [28]:
# create a tensor with all zeroes
zeros = torch.zeros(size = (3,4))
random_tensor=torch.rand(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
#create a tensor of ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype #default datatype always this type

torch.float32

###creating a range of tensors and tensors-like

In [32]:
torch.range(0,10) #may or may not be depricated
torch.__version__
torch.arange(0,10)

<ipython-input-32-4099aec020e2>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10) #may or may not be depricated


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
one_to_ten = torch.arange(1,11)
one_to_ten = torch.arange(start=0,end=1000, step =77)
one_to_ten = torch.arange(start=1,end=11, step =1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten) #zeros in the same shape a one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatype

***Note:*** Tensor datatypes isone of the 3 big errors that you'll run into with PyTorch and DL;
1. Tensors not right data type
2. Tensors not right shape (matrix mul)
3. Tensors not on the right device



In [35]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_32_tensor.dtype #even though dtype is none it is still by default float32

torch.float16

In [37]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [38]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tensor, eg float32,float16 doc@torch.tensor - precision in computing
                               device=None, #what device your tensors on ; cpu by default; cuda for gpu - device agnostic codes; eg opns on two tensors feom diff gpu's/cpus
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor #coverted our float32 tensor to float16

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor * float_32_tensor #it works but some opns might not

tensor([ 9., 36., 81.])

In [41]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [43]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [44]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting info from tensors - tensor attributes
1. Tensors not right data type - to get datatype from tensor, can use tensor.dtype
2. Tensors not right shape (matrix mul) - to get shape frpm tensor, can use tensor.shape
3. Tensors not on the right device - to get device from tensor, can use tensor.device


In [45]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6518, 0.7389, 0.1440, 0.7296],
        [0.2477, 0.8236, 0.8930, 0.0706],
        [0.4332, 0.9913, 0.1921, 0.5471]])

In [46]:
#find details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6518, 0.7389, 0.1440, 0.7296],
        [0.2477, 0.8236, 0.8930, 0.0706],
        [0.4332, 0.9913, 0.1921, 0.5471]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition, subtraction, multiplication (el-wise), division, multiplication

In [47]:
#Elemntwise mm
tensor = torch.tensor([1,2,3])
print(tensor, "*", tensor)
tensor.dtype()

tensor([1, 2, 3]) * tensor([1, 2, 3])


TypeError: 'torch.dtype' object is not callable